### ISSUE TITLE
Page not found on Github.

### ISSUE THREAD

**Issue by sagarhani** [jee1mr/whatcanidoforfsmk#1] opened 2015-01-05 05:18 UTC
On clicking on "Why not make some changes?" directs you to Page not found. 
![page not found](https://cloud.githubusercontent.com/assets/6933389/5609527/3faff3b6-94c8-11e4-8edd-1d12a5a98b1e.png)

**Comment by jee1mr** [comment] 2015-01-05 05:35
@sagarhani Thanks. The issue is fixed now :+1:

**Closed** 2015-01-05 05:54 UTC
Labels: bug
